export const ACCION_LABEL: Record<string, string> = {
  CREACION: 'Creación',
  ASIGNACION: 'Salida inicial',
  EDICION: 'Edición',
  TRANSFERENCIA: 'Cambio de oficina asignada',
  ENVIO_SOPORTE: 'Entrada',
  RETORNO_SOPORTE: 'Salida',
  ENVIO_SERVICIO_EXTERNO: 'Envío a Servicio',
  RETORNO_SERVICIO_EXTERNO: 'Retorno de Servicio',
  PRESTAMO: 'Préstamo',
  DEVOLUCION: 'Devolución',
  CAMBIO_ESTADO: 'Cambio de Estado',
  FOTO_AGREGADA: 'Foto agregada',
  FOTO_ELIMINADA: 'Foto eliminada',
};

export const ACCION_COLOR: Record<string, string> = {
  CREACION: 'success',
  EDICION: 'info',
  ASIGNACION: 'primary',
  TRANSFERENCIA: 'primary',
  ENVIO_SOPORTE: 'warning',
  RETORNO_SOPORTE: 'success',
  ENVIO_SERVICIO_EXTERNO: 'warning',
  RETORNO_SERVICIO_EXTERNO: 'success',
  PRESTAMO: 'info',
  DEVOLUCION: 'success',
  CAMBIO_ESTADO: 'neutral',
  FOTO_AGREGADA: 'info',
  FOTO_ELIMINADA: 'neutral',
};

export const ACCION_OPTIONS = [
  { value: '', label: 'Todas las acciones' },
  { value: 'CREACION', label: 'Creación' },
  { value: 'ASIGNACION', label: 'Salida inicial' },
  { value: 'EDICION', label: 'Edición' },
  { value: 'TRANSFERENCIA', label: 'Cambio de oficina asignada' },
  { value: 'ENVIO_SOPORTE', label: 'Entrada' },
  { value: 'RETORNO_SOPORTE', label: 'Salida' },
  { value: 'ENVIO_SERVICIO_EXTERNO', label: 'Envío a Servicio Externo' },
  { value: 'RETORNO_SERVICIO_EXTERNO', label: 'Retorno de Servicio' },
  { value: 'PRESTAMO', label: 'Préstamo' },
  { value: 'DEVOLUCION', label: 'Devolución' },
  { value: 'CAMBIO_ESTADO', label: 'Cambio de Estado' },
];
